FROM jenkins/jenkins:lts-jdk17

USER root

# Install Docker CLI static binary so Jenkins can trigger containerized build/test steps
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-26.1.4.tgz -o docker.tgz \
    && tar xzvf docker.tgz \
    && mv docker/docker /usr/local/bin/ \
    && rm -rf docker docker.tgz

# Allow git operations across workspace directories with different ownership
RUN git config --global --add safe.directory '*'

